In [3]:
# Introduction to Numpy

In [1]:
import numpy as np

In [2]:
mylist = [13, 52, -23]
x = np.array(mylist)
x

array([ 13,  52, -23])

In [3]:
y = np.array([3, 4, 5])
y

array([3, 4, 5])

In [5]:
m = np.array ([[9, 10, 11], [-3, 0, -4]])
m

array([[ 9, 10, 11],
       [-3,  0, -4]])

In [7]:
m.shape

(2, 3)

In [10]:
n = np.arange (0, 56, 5)
n

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [12]:
n = n.reshape(3,4)
n

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [17]:
o = np.linspace (0, 10, 21)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
o.resize (7,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. ]])

In [32]:
x

array([ 13,  52, -23])

In [33]:
y

array([3, 4, 5])

In [25]:
x + y

array([ 16,  56, -18])

In [26]:
x * y

array([  39,  208, -115])

In [27]:
x **2

array([ 169, 2704,  529], dtype=int32)

In [28]:
x.dot(y) #dot product in linear algebra

132

In [34]:
z = np.array([y, y**2])
z

array([[ 3,  4,  5],
       [ 9, 16, 25]])

In [35]:
z.shape

(2, 3)

In [36]:
z.T #transpose

array([[ 3,  9],
       [ 4, 16],
       [ 5, 25]])

In [37]:
z.T.shape

(3, 2)

In [38]:
z.dtype

dtype('int32')

In [39]:
z = z.astype ('f') #change from int to float
z.dtype

dtype('float32')

In [40]:
a = np.array ([-23, -1, 0, 2, 56, 123])
a.sum()

157

In [41]:
a.max()

123

In [42]:
a.min()

-23

In [45]:
a.mean()

26.166666666666668

In [47]:
a.std() #standard deviation

49.48203939029011

In [48]:
a.argmax()

5

In [55]:
a.argmin()

0

## Indexing/Slicing

In [53]:
s = np.arange(12)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [54]:
s[0], s[4], s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

In [56]:
 s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [57]:
s[-4:]

array([ 64,  81, 100, 121], dtype=int32)

In [58]:
r = np.arange(36) #create an array from 0 to 35
r.resize (6,6) #resize the array to a 6 b y 6 matrix
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [59]:
r [3,4] #return the value of fourth row, fifth column

22

In [61]:
r [4, 3:6] #fifth row, fourth, fifth, and sixth elements

array([27, 28, 29])

In [64]:
r [-1, :3]

array([30, 31, 32])

In [66]:
r[r>12] #conditional slicing

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35])

In [68]:
r [r>30] = 30 #return the original array but everything >30, will be 30
r #capping at 30

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [69]:
r2 = r[:3, :3] #slide r to make r2
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [70]:
r2[:] = 0 #set every element of r2 to 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
r #part of r is now changed as well

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [72]:
r_c = r.copy() #set a copy of r 
r_c

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [73]:
r_c[:] = 10 #set every element of r_c to 10
r_c

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [84]:
r #r does not change

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [90]:
r[2:4,2:4]


array([[ 0, 15],
       [20, 21]])

# Iterating Over Arrays 

In [75]:
test = np.random.randint (0, 10, (4,3)) #create a 4 by 3 arrange from random numbers 0-9
test

array([[4, 8, 9],
       [6, 5, 8],
       [8, 4, 6],
       [0, 3, 2]])

In [76]:
for a in test: #go through all elements in array
    print (a)

[4 8 9]
[6 5 8]
[8 4 6]
[0 3 2]


In [79]:
for ii in range(len(test)):
    print (test[ii])

[4 8 9]
[6 5 8]
[8 4 6]
[0 3 2]


In [81]:
for i, row in enumerate (test):
    print ('row', i, 'is', row)

row 0 is [4 8 9]
row 1 is [6 5 8]
row 2 is [8 4 6]
row 3 is [0 3 2]


In [82]:
test2 = test **2
test2

array([[16, 64, 81],
       [36, 25, 64],
       [64, 16, 36],
       [ 0,  9,  4]], dtype=int32)

In [83]:
for i, j in zip (test, test2): #reiterate through both arrays
    print (i, '+', j, '=', i+j)

[4 8 9] + [16 64 81] = [20 72 90]
[6 5 8] + [36 25 64] = [42 30 72]
[8 4 6] + [64 16 36] = [72 20 42]
[0 3 2] + [0 9 4] = [ 0 12  6]


In [91]:
 ['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]